name: Timberella
version: ${version}
main: com.github.hrobasti.timberella.TimberellaPlugin
description: "Tree cutting, leaves decay and replanting abilities. Completely configurable."
api-version: '1.21'
authors:
  - hro_basti
website: "https://github.com/hrobasti/timberella-plugin"
permissions:
  timberella.use:
    description: Use Timberella to fell trees
    default: true
  timberella.toggle:
    description: Allow players to toggle Timberella for themselves
    default: true
  timberella.admin:
    description: Admin permission for Timberella
    default: op
  timberella.update.notify:
    description: Receive in-game update reminders when new versions are available
    default: op
